<?php

/**
 * @file
 * Contains all_lives.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function all_lives_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the all_lives module.
    case 'help.page.all_lives':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Page affichant tous les concerts') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function all_lives_theme() {
  return [
    'all_lives' => [
      'variables' => [
        'var' => [],
      ],
    ],
  ];
}
